export const COLORS = {
  mainTheme: "#55c7aa",
  black: "black",
  white: "white",
  grey: "grey",
  lightGrey: "lightgrey",
  red: "#f44336",
  reviewStar: "#fdcc0d",
  offeredText: "#ff9529",
  requestedText: "#55aacc",
  borderColor: "#ddd",
  shadowColor: "#000",
  borderBottomColor: "#ccc",
  dateColor: "#666",
  nonEditableColor: "#f0f0f0",
  editPhotoButtonColor: "#ff9529",
};
